/**
 * ${descriptionFr!"Modèle " + className}
 *
 * @generated by GUCE Low-Code Generator
 * @version ${generatorVersion}
 */

// === GENERATED CODE START - DO NOT MODIFY ===

export interface ${className} {
  id?: string;
<#list attributes as attr>
  ${attr.name}<#if !attr.isRequired>?</#if>: <#if attr.dataType.name() == "STRING" || attr.dataType.name() == "TEXT" || attr.dataType.name() == "EMAIL" || attr.dataType.name() == "PHONE" || attr.dataType.name() == "URL" || attr.dataType.name() == "ENUM">string<#elseif attr.dataType.name() == "INTEGER" || attr.dataType.name() == "LONG" || attr.dataType.name() == "DECIMAL" || attr.dataType.name() == "CURRENCY" || attr.dataType.name() == "PERCENTAGE">number<#elseif attr.dataType.name() == "BOOLEAN">boolean<#elseif attr.dataType.name() == "DATE" || attr.dataType.name() == "TIME" || attr.dataType.name() == "DATETIME">Date<#else>any</#if>;
</#list>
<#list relations as rel>
  ${rel.name}<#if !rel.isRequired>?</#if>: <#if rel.relationType.name() == "ONE_TO_MANY" || rel.relationType.name() == "MANY_TO_MANY">${rel.targetEntity.className}[]<#else>${rel.targetEntity.className}</#if>;
</#list>
  createdAt?: Date;
  updatedAt?: Date;
  createdBy?: string;
}

export interface ${className}CreateRequest {
<#list attributes as attr>
<#if attr.isFormVisible>
  ${attr.name}<#if !attr.isRequired>?</#if>: <#if attr.dataType.name() == "STRING" || attr.dataType.name() == "TEXT" || attr.dataType.name() == "EMAIL" || attr.dataType.name() == "PHONE" || attr.dataType.name() == "URL" || attr.dataType.name() == "ENUM">string<#elseif attr.dataType.name() == "INTEGER" || attr.dataType.name() == "LONG" || attr.dataType.name() == "DECIMAL" || attr.dataType.name() == "CURRENCY" || attr.dataType.name() == "PERCENTAGE">number<#elseif attr.dataType.name() == "BOOLEAN">boolean<#elseif attr.dataType.name() == "DATE" || attr.dataType.name() == "TIME" || attr.dataType.name() == "DATETIME">Date<#else>any</#if>;
</#if>
</#list>
}

export interface ${className}UpdateRequest {
<#list attributes as attr>
<#if attr.isFormVisible>
  ${attr.name}?: <#if attr.dataType.name() == "STRING" || attr.dataType.name() == "TEXT" || attr.dataType.name() == "EMAIL" || attr.dataType.name() == "PHONE" || attr.dataType.name() == "URL" || attr.dataType.name() == "ENUM">string<#elseif attr.dataType.name() == "INTEGER" || attr.dataType.name() == "LONG" || attr.dataType.name() == "DECIMAL" || attr.dataType.name() == "CURRENCY" || attr.dataType.name() == "PERCENTAGE">number<#elseif attr.dataType.name() == "BOOLEAN">boolean<#elseif attr.dataType.name() == "DATE" || attr.dataType.name() == "TIME" || attr.dataType.name() == "DATETIME">Date<#else>any</#if>;
</#if>
</#list>
}

<#list attributes as attr>
<#if attr.dataType.name() == "ENUM">
export enum ${attr.name?cap_first} {
<#list attr.enumValues?split(",") as val>
  ${val?trim} = '${val?trim}'<#if val_has_next>,</#if>
</#list>
}

</#if>
</#list>
// === GENERATED CODE END ===

// @CUSTOM_START
// Zone de code personnalisé - Préservée lors de la régénération
// @CUSTOM_END
