import { Injectable } from '@angular/core';
import { HttpClient, HttpParams } from '@angular/common/http';
import { Observable } from 'rxjs';
import { environment } from '@env/environment';
import { ApiResponse, PaginatedResponse } from '@core/models/api-response.model';
import { ${className}, ${className}CreateRequest, ${className}UpdateRequest } from '../models/${camelCaseName}.model';

/**
 * Service ${className}
 *
 * @generated by GUCE Low-Code Generator
 * @version ${generatorVersion}
 */
@Injectable({
  providedIn: 'root'
})
export class ${className}Service {

  private readonly baseUrl = `<#noparse>${environment.apiUrl}</#noparse>${apiPath}`;

  constructor(private http: HttpClient) {}

  // === GENERATED CODE START - DO NOT MODIFY ===

  /**
   * Récupère la liste des ${camelCaseName}s
   */
  findAll(): Observable<ApiResponse<${className}[]>> {
    return this.http.get<ApiResponse<${className}[]>>(this.baseUrl);
  }

  /**
   * Récupère un ${camelCaseName} par son ID
   */
  findById(id: string): Observable<ApiResponse<${className}>> {
    return this.http.get<ApiResponse<${className}>>(`<#noparse>${this.baseUrl}/${id}</#noparse>`);
  }

<#if generateSearch>
  /**
   * Recherche des ${camelCaseName}s
   */
  search(query: string, page = 0, size = 20): Observable<PaginatedResponse<${className}>> {
    const params = new HttpParams()
      .set('q', query)
      .set('page', page.toString())
      .set('size', size.toString());
    return this.http.get<PaginatedResponse<${className}>>(`<#noparse>${this.baseUrl}/search</#noparse>`, { params });
  }
</#if>

<#if generateCrud>
  /**
   * Crée un nouveau ${camelCaseName}
   */
  create(request: ${className}CreateRequest): Observable<ApiResponse<${className}>> {
    return this.http.post<ApiResponse<${className}>>(this.baseUrl, request);
  }

  /**
   * Met à jour un ${camelCaseName}
   */
  update(id: string, request: ${className}UpdateRequest): Observable<ApiResponse<${className}>> {
    return this.http.put<ApiResponse<${className}>>(`<#noparse>${this.baseUrl}/${id}</#noparse>`, request);
  }

  /**
   * Supprime un ${camelCaseName}
   */
  delete(id: string): Observable<void> {
    return this.http.delete<void>(`<#noparse>${this.baseUrl}/${id}</#noparse>`);
  }
</#if>

  // === GENERATED CODE END ===

  // @CUSTOM_START
  // Zone de code personnalisé - Préservée lors de la régénération
  // @CUSTOM_END
}
