package cm.guce.${moduleName}.application.service;

import cm.guce.common.domain.exception.ResourceNotFoundException;
import cm.guce.common.domain.exception.ValidationException;
import cm.guce.common.security.SecurityUtils;
import cm.guce.${moduleName}.application.dto.${className}Dto;
import cm.guce.${moduleName}.application.mapper.${className}Mapper;
import cm.guce.${moduleName}.domain.model.${className};
import cm.guce.${moduleName}.domain.port.${className}Repository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;
import java.util.UUID;

/**
 * Service de gestion des ${camelCaseName}s.
 *
 * @generated by GUCE Low-Code Generator
 * @version ${generatorVersion}
 */
@Slf4j
@Service
@RequiredArgsConstructor
@Transactional(readOnly = true)
public class ${className}Service {

    private final ${className}Repository ${camelCaseName}Repository;
    private final ${className}Mapper ${camelCaseName}Mapper;

${generatedStart}

    /**
     * Récupère tous les ${camelCaseName}s.
     */
    public List<${className}Dto.Response> findAll() {
        log.debug("Fetching all ${camelCaseName}s");
        return ${camelCaseName}Mapper.toResponseList(${camelCaseName}Repository.findAll());
    }

    /**
     * Récupère un ${camelCaseName} par son ID.
     */
    public ${className}Dto.Response findById(UUID id) {
        log.debug("Fetching ${camelCaseName} by id: {}", id);
        ${className} entity = ${camelCaseName}Repository.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("${className}", id));
        return ${camelCaseName}Mapper.toResponse(entity);
    }

<#if generateSearch>
    /**
     * Recherche de ${camelCaseName}s.
     */
    public Page<${className}Dto.Response> search(String query, Pageable pageable) {
        log.debug("Searching ${camelCaseName}s with query: {}", query);
        return ${camelCaseName}Repository.search(query, pageable)
                .map(${camelCaseName}Mapper::toResponse);
    }
</#if>

<#if generateCrud>
    /**
     * Crée un nouveau ${camelCaseName}.
     */
    @Transactional
    public ${className}Dto.Response create(${className}Dto.CreateRequest request) {
        log.info("Creating new ${camelCaseName}");

        validateCreate(request);

        ${className} entity = ${camelCaseName}Mapper.toEntity(request);
        entity.setTenantId(SecurityUtils.getCurrentTenantId().orElse("default"));

        entity = ${camelCaseName}Repository.save(entity);
        log.info("${className} created with id: {}", entity.getId());

        return ${camelCaseName}Mapper.toResponse(entity);
    }

    /**
     * Met à jour un ${camelCaseName}.
     */
    @Transactional
    public ${className}Dto.Response update(UUID id, ${className}Dto.UpdateRequest request) {
        log.info("Updating ${camelCaseName}: {}", id);

        ${className} entity = ${camelCaseName}Repository.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("${className}", id));

        ${camelCaseName}Mapper.updateEntity(request, entity);
        entity = ${camelCaseName}Repository.save(entity);

        log.info("${className} updated: {}", entity.getId());
        return ${camelCaseName}Mapper.toResponse(entity);
    }

    /**
     * Supprime un ${camelCaseName}.
     */
    @Transactional
    public void delete(UUID id) {
        log.info("Deleting ${camelCaseName}: {}", id);

        ${className} entity = ${camelCaseName}Repository.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("${className}", id));

    <#if generateSoftDelete!true>
        entity.softDelete(SecurityUtils.getCurrentUserId().orElse("SYSTEM"));
        ${camelCaseName}Repository.save(entity);
    <#else>
        ${camelCaseName}Repository.delete(entity);
    </#if>

        log.info("${className} deleted: {}", id);
    }

    private void validateCreate(${className}Dto.CreateRequest request) {
        ValidationException validationException = new ValidationException("Erreur de validation");

        // Ajoutez vos validations ici

        if (validationException.hasErrors()) {
            throw validationException;
        }
    }
</#if>
${generatedEnd}

${customStart}
    // Zone de code personnalisé - Préservée lors de la régénération
    // Ajoutez ici vos méthodes de service personnalisées
${customEnd}
}
